  // ---------- Definitions ----------
  const DEFS = [
    ['Container', 'A Linux process running with its own view of filesystem, network, and namespaces — packaged with the dependencies it needs to run.'],
    ['Image', 'A read-only template of layers used to start containers. Immutable and content-addressed.'],
    ['Pod', 'Kubernetes\' smallest deployable unit — one or more tightly-coupled containers sharing network and storage.'],
    ['Node', 'A machine (physical or virtual) in a Kubernetes cluster that runs Pods.'],
    ['Namespace (K8s)', 'A logical partition of a Kubernetes cluster for names, quotas, and RBAC.'],
    ['Deployment', 'A K8s object that manages a ReplicaSet and handles rolling updates and rollbacks.'],
    ['Service (K8s)', 'A stable virtual IP and DNS name that load-balances to Pods matched by labels.'],
    ['Ingress', 'HTTP(S) routing on top of Services, driven by an Ingress Controller (nginx-ingress, Traefik, etc.).'],
    ['Chart (Helm)', 'A package of templated Kubernetes manifests plus a values file — distributable as a tarball.'],
    ['Release (Helm)', 'A named installation of a chart into a cluster, with a revision history.'],
    ['Provider (Terraform)', 'A plugin that translates HCL into API calls against a specific platform (aws, google, azurerm...).'],
    ['State (Terraform)', 'The mapping between your Terraform code and the real resources it manages.'],
    ['Playbook (Ansible)', 'A YAML file that binds tasks to hosts and describes desired state.'],
    ['Idempotent', 'An operation whose repeated application yields the same end state as one application.'],
    ['GitOps', 'Using a Git repo as the single source of truth for infrastructure, with a controller reconciling reality to match.'],
    ['Runner', 'A machine (VM, container, self-hosted host) that actually executes a CI job.'],
    ['Artifact', 'A versioned, packaged output of a build — binary, container image, tarball — stored in a registry.'],
    ['Pipeline', 'The scripted sequence a change moves through: build → test → deploy.'],
    ['Reverse Proxy', 'A server that receives client requests and forwards them to backends, hiding the backends from clients.'],
    ['TLS Termination', 'Decrypting HTTPS at the edge so backends can speak plain HTTP internally.'],
    ['A Record', 'A DNS record mapping a hostname to an IPv4 address.'],
    ['CNAME', 'An alias from one DNS name to another name (never directly to an IP).'],
    ['TTL', 'Time-To-Live: how long a resolver may cache a DNS record.'],
    ['SSL / TLS', 'A protocol that encrypts and authenticates TCP connections. SSL is the deprecated older name; modern deployments are TLS 1.2 or 1.3.'],
    ['Certificate', 'A public key bound to an identity (a domain name), signed by a certificate authority.'],
    ['mTLS', 'Mutual TLS — both client and server present certificates.'],
    ['RBAC', 'Role-Based Access Control: permissions attach to roles, roles assign to principals.'],
    ['IAM', 'Identity and Access Management — the cloud vendor name for authentication + authorization.'],
    ['Service Account', 'A non-human identity attached to a workload so it can authenticate to APIs.'],
    ['Least Privilege', 'Grant each principal only the permissions it actually needs — nothing more.'],
    ['Read Replica', 'A follower database that streams writes from the primary and serves read traffic.'],
    ['Connection Pool', 'A pre-established set of DB connections shared across many application requests.'],
    ['ProxySQL', 'A MySQL-aware proxy that pools connections, routes reads to replicas, and hides failover from the app.'],
    ['PgBouncer', 'A lightweight connection pooler for PostgreSQL.'],
    ['Migration', 'A versioned change to database schema, applied and tracked in order (Flyway, Alembic, Rails migrations...).'],
    ['systemd', 'The init system on modern Linux, managing services, timers, and system state.'],
    ['journalctl', 'The reader for systemd\'s structured log journal.'],
    ['SIGTERM', 'A signal politely asking a process to shut down. Catchable — the process gets time to clean up.'],
    ['SIGKILL', 'A signal that kills a process immediately. Uncatchable.'],
    ['Lockfile', 'A file that pins exact resolved dependency versions for reproducible installs.'],
    ['Semver', 'Version scheme MAJOR.MINOR.PATCH. Major = breaking; minor = features; patch = fixes.'],
    ['Composer', 'The dependency manager for PHP, using composer.json and Packagist.'],
    ['Rebase', 'Replays commits on top of another branch, giving linear history.'],
    ['Reflog', 'A log of every position HEAD has occupied — the safety net for recovering lost commits.'],
    ['REST', 'An architectural style for HTTP APIs: resources at URLs, verbs by HTTP method, state in the response body.'],
    ['Idempotent (HTTP)', 'A method that produces the same effect if called twice — GET, PUT, DELETE. POST is not.'],
    ['SSE', 'Server-Sent Events: one-way streaming from server to browser over HTTP, with automatic reconnect.'],
    ['WebSocket', 'A two-way persistent connection over a single TCP socket. Use when the client also pushes frequently.'],
    ['SDK', 'Software Development Kit — a language-specific client library that wraps an API.'],
    ['Region (Cloud)', 'A geographic cloud location containing multiple availability zones.'],
    ['Availability Zone', 'An isolated datacentre within a cloud region.'],
    ['VPC', 'Virtual Private Cloud — an isolated network in your cloud account, sliced into subnets.'],
    ['Subnet', 'A range of IP addresses within a VPC, marked public or private by its routing.'],
    ['Security Group', 'A stateful cloud firewall attached to instances or ENIs. Return traffic is auto-allowed.'],
    ['NAT Gateway', 'A managed service that lets private-subnet resources reach the internet without being reachable from it.'],
    ['WAF', 'Web Application Firewall — inspects HTTP traffic and blocks OWASP-style attacks (SQLi, XSS, path traversal).'],
    ['OWASP Top 10', 'The reference list of the most common web application vulnerability classes.'],
    ['CSRF', 'Cross-Site Request Forgery — tricking a logged-in browser into using its own credentials to make a request.'],
    ['XSS', 'Cross-Site Scripting — injecting script that runs in another user\'s browser session under your origin.'],
    ['SQL Injection', 'Coercing a database into running attacker-supplied SQL by concatenating input into queries.'],
    ['VPN', 'An encrypted tunnel joining two networks, or a client to a network.'],
    ['WireGuard', 'A modern, minimal, fast VPN protocol using public-key crypto.'],
    ['BGP', 'Border Gateway Protocol — how autonomous systems on the internet exchange routes.'],
    ['VPC Peering', 'A direct connection between two VPCs so they can route to each other privately.'],
    ['Transit Gateway', 'A cloud hub that connects many VPCs and on-prem networks with one routing table.'],
    ['PromQL', 'Prometheus\'s functional query language over time series.'],
    ['SLI', 'Service Level Indicator — the measurement of a service\'s behaviour (e.g., % of requests under 200 ms).'],
    ['SLO', 'Service Level Objective — the target for an SLI over a window (e.g., 99.9% over 30 days).'],
    ['SLA', 'Service Level Agreement — the external contract, usually with penalties for missing it.'],
    ['Trace', 'The recorded path of a single request as it moves across services, split into spans.'],
    ['Span', 'One unit of work inside a trace — a service, an operation, a duration, some attributes.'],
    ['MCP', 'Model Context Protocol — an open standard for exposing tools, resources, and prompts to LLM agents.'],
    ['phpMyAdmin', 'A long-standing web UI for administering MySQL/MariaDB databases.'],
    ['Caddy', 'A modern reverse-proxy server whose signature feature is automatic HTTPS via Let\'s Encrypt.'],
    ['SNI', 'Server Name Indication — a TLS extension letting a client tell the server which hostname it wants during the handshake.'],
    ['Mount', 'Attaching a filesystem to a directory in the unified tree. <code>mount /dev/sdb1 /data</code> makes that disk visible under <code>/data</code>. <code>/etc/fstab</code> makes mounts persist across reboots.'],
    ['Symlink', 'A symbolic link — a small file containing a path pointing at another path, resolved at access time. <code>ln -s target link</code>. Breaks if the target moves. The nginx <code>sites-enabled → sites-available</code> pattern is symlinks.'],
    ['Hard link', 'A second directory entry for the same inode — same file, two names. <code>ln target link</code>. Cannot cross filesystems, cannot link directories. Deleting one leaves the other working.'],
    ['Inode', 'The Linux filesystem\'s internal record for a file — permissions, timestamps, size, block pointers. Filenames are just directory entries pointing to inodes. Run out of inodes and you can\'t create files even with disk space free. <code>ls -i</code> shows them; <code>df -i</code> shows inode usage.'],
  ];

